services:
  app:
    build:
      context: .
      dockerfile: infra/docker/app/Dockerfile
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=portfolio

  db:
    build:
      context: .
      dockerfile: infra/docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: portfolio
    ports:
      - 3306:3306
    volumes:
      - ./_shared_data/mysql_data/:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1s
      timeout: 5s
      retries: 30
